### ISSUE TITLE
Can't read detail blog from second

### ISSUE THREAD

**Issue by nqtuyen** [oqtane/oqtane.blogs#10] opened 2021-01-21 02:27 UTC
When I add more than one blog, I can not browse it because of always return first item.

<h2>@_blogs[0].Title</h2>

pls review it.
Thank so much.

**Comment by sbwalker** [comment] 2021-02-04 14:16
Caused by issue #9, fixed in #11

**Closed by sbwalker** 2021-02-04 14:16 UTC
